server:
  port: 80


eureka:
  client:
    # 表示将自己注册到服务中心
    register-with-eureka: true
    #true 表示将从注册中心抓取已有的注册信息，默认为true，单节点影响不大，但是集群必须设置为true才能配合ribbon使用负载均衡
    fetch-registry: true
    service-url:
      # 设置与eureka server交互的地址查询服务和注册服务都需要依赖这个地址
      defaultZone: http://localhost:7001/eureka/
spring:
  application:
    name: cloud-order-consume