server:
  port: 80


eureka:
  client:
    # 表示将自己注册到服务中心
    register-with-eureka: true
    #true 表示将从注册中心抓取已有的注册信息，默认为true，单节点影响不大，但是集群必须设置为true才能配合ribbon使用负载均衡
    fetch-registry: true
    service-url:
      # 设置与eureka server交互的地址查询服务和注册服务都需要依赖这个地址
      defaultZone: http://localhost:7001/eureka/

  instance:
    instance-id: oerder1
    # 访问路径可以显示IP地址
    prefer-ip-address: true
    # Eureka 客户端向服务端发送心跳的时间间隔，单位为秒（默认为30s）
    lease-renewal-interval-in-seconds: 10
    # Eureka 服务端在收到最后一次心跳后等待的时间上线，单位为秒（默认是90） 超时将剔除服务
    lease-expiration-duration-in-seconds: 10

spring:
  application:
    name: cloud-order-consume